### ISSUE TITLE
VibranceGUI updated, hash invalidated

### ISSUE THREAD

**Issue by disco0** [2m/vibrance-gui-nuget#3]
VibranceGUI's been bumped to 2.3.1.1, any chance the package can get an update? Seems the only thing that actually needs an update (besides version info) is the hash.

PS: To those with the same problem—until there's another update to vibranceGUI install with the correct hash added to the install command:
````choco install vibrancegui --download-checksum='52C9E0D6ECCC71FB71337124325D1BA0A3B2D502'````

**Comment by 2m** [comment]
Thanks. Created PR to fix this. Lets see if the automatic publishing from appveyor still works. ;)

**Comment by 2m** [comment]
Can't get the publish from AppVeyor working. If you can please take a look. Otherwise I'll get back to this later.

**Comment by disco0** [comment]
np, made an fork earlier before I noticed you were on it so I'll give it a look
